# fly.toml app configuration file generated for news-extract-app on 2024-01-10T22:23:40-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "news-extract-app-fly"
primary_region = "atl"

[build]

[http_service]
  internal_port = 3000   
  protocol = "tcp"
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services.ports]]
  handlers = ["http"]
  port = 3000   

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
